const blacklist_spotify_servers = [
	"aet.spotify.com",
	"enduser.adsrvr.org",
	"de2-bid.adsrvr.org",
	//"api-partner.spotify.com", // breaks UI
	"spclient.wg.spotify.com", // careful.. break social features, chrome cast, android app
	//"gew1-spclient.spotify.com", // necessary to play songs
	//"https://spclient.wg.spotify.com/ads/**",
	//"https://spclient.wg.spotify.com/ad-logic/*",
	"adeventtracker.spotify.com",
	"ads-akp.spotify.com",
	"audio-ak.spotify.com",
	"audio-akp.spotify.com",
	"analytics.spotify.com",
	"assets.spotify.com",
	"audio-cf.spotify.com",
	"audio-fa.scdn.co",
	"audio-fa.spotify.com",
	"audio-fab.spotify.com",
	"audio-fac-spotify.com",
	"audio-gc.scdn.co",
	"audio-gc.spotify.com",
	"crashdump.spotify.com",
	"crashdump.ciqe-gslb.spotify.com",
	"heads-ak.spotify.com",
	"heads-akp.spotify.com",
	"heads-cf.spotify.com",
	"heads-fa.scdn.co",
	"heads-fa.spotify.com",
	"heads-fab.spotify.com",
	"heads-fac.spotify.com",
	"links.spotify.com",
	"log.spotify.com",
	"log2.spotify.com",
	"mp3ad.scdn.co",
	"partner-service.spotify.com",
	"partner-service-testing.spotify.com",
	"payment-callback.spotify.com",
	"pci.spotify.com",
	"pixel.spotify.com",
	"upgrade.scdn.co",
	"upgrade.spotify.com",
	"video-fa.scdn.co",
	"video-fa.cdn.spotify.com",
	"video-fa-b.cdn.spotify.com",
];

export default blacklist_spotify_servers;
export { blacklist_spotify_servers };
